version: "3.7"
services:
  emby:
    image: lscr.io/linuxserver/emby:latest
    container_name: umbrel-emby
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
    volumes:
      - ./data:/config
      - ./media:/media
    ports:
      - "8096:8096"
    restart: unless-stopped
