version: '3.8'
services:
  emby:
    image: emby/embyserver:latest
    container_name: emby
    network_mode: "host"
    environment:
      - UID=1000
      - GID=1000
      - TZ=Europe/Rome
    volumes:
      - /mnt/data/emby/config:/config
      - /mnt/data/emby/media:/media
      - /mnt/data/emby/data:/data
    restart: unless-stopped
